services:
  - type: web
    name: forestsathi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
